### ISSUE TITLE
purpose of package?

### ISSUE THREAD

**Issue by goerz** [conda-forge/texlive-core-feedstock#14]
I may be misunderstanding the purpose of this package. I had hoped that `conda install texlive-core` would install `latex` into my conda environment. In my situation, I need `latex` on TravisCI. So far, I've solved this by installing texlive through `apt-get`, but this is extremely slow. Therefore, I was hoping to install texlive through `conda` instead.

However, after installing `texlive-core`, there is no `latex` or `pdflatex` executable in the `bin` folder of my conda environment (there is a `tex` binary, however). Am I missing a step?

**Comment by ocefpaf** [comment]
It builds `tex` and `pdftex`. I did got a suggestion to symlink those to `latex` and `pdflatex` but I never looked into that option nor if `texlive`builds/symlinks those if we add some optional flag.

**Comment by goerz** [comment]
Hmm.. but tex and latex aren't the same, are they? Is symlinking them enough? In any case, I tried just linking tex -> latex; it gives me an error like the following:

    pyx.text.TexResultError: TeX didn't respond as expected within the timeout period.
    The expression passed to TeX was:
      \scrollmode
       ...
      \PyXInput{1}%
    After parsing the return message from TeX, the following was left:
      This is TeXk, Version 3.14159265 (TeX Live 2016) (preloaded format=latex)
       restricted \write18 enabled.
      **
      kpathsea: Running mktexfmt latex.fmt
      Can't locate mktexlsr.pl in @INC (@INC contains: /home/travis/miniconda/envs/test-environment/share/texlive/tlpkg /home/travis/miniconda/envs/test-environment/share/texlive/texmf-dist/scripts/texlive /home/travis/miniconda/envs/test-environment/lib/perl5/site_perl/5.20.3/x86_64-linux-thread-multi /home/travis/miniconda/envs/test-environment/lib/perl5/site_perl/5.20.3 /home/travis/miniconda/envs/test-environment/lib/perl5/5.20.3/x86_64-linux-thread-multi /home/travis/miniconda/envs/test-environment/lib/perl5/5.20.3 .) at /home/travis/miniconda/envs/test-environment/bin/mktexfmt line 23.
      (cut after 5 lines; use errordetail.full for all output)

**Comment by ocefpaf** [comment]
I guess that both are `pdftex`. This is on my Linux machine texlive package:

```
> which latex
/usr/bin/latex
> file /usr/bin/latex
/usr/bin/latex: symbolic link to `pdftex'
```

```
> which pdflatex
/usr/bin/pdflatex
> file /usr/bin/pdflatex
/usr/bin/latex: symbolic link to `pdftex'
```

**Comment by goerz** [comment]
Interesting! So this *should* work then, I just have to figure out what's going on with the Perl script. It's probably some environment variable that needs to be set.

**Comment by bgruening** [comment]
Any updates on this. There are also a few PR open that could be merge @ocefpaf.
Thanks!

**Comment by ocefpaf** [comment]
I'll send a PR to add the symlinks. I guess that is the best solution here since most people expect to find pdflatex and latex.

**Comment by hugobuddel** [comment]
Still unclear to me what the purpose of the package is. I've created a very simple `test.tex`:

    The quadratic formula is $-b \pm \sqrt{b^2 - 4ac} \over 2a$
    \bye

Should it be possible to do `tex test` or `pdftex test` after installing `texlive-core`?

At my machine it doesn't, I get these two errors:

    warning: kpathsea: configuration file texmf.cnf not found in these directories:

which was fixed with

    ln -s "${CONDA_PREFIX}/share/texlive/texmf-dist" "${CONDA_PREFIX}/share/texmf-dist"

and

    I can't find the format file `tex.fmt'!

Should I make issues for these problems or am I misunderstanding what this package is supposed to do?

**Comment by yichao-cai** [comment]
I am having the same issue.

I have installed `texlive-core` using `conda`.
When I tried to run `pandoc text.md -o text.pdf`, it complains that it can not find configuration files:
> kpathsea: Running mktexfmt pdflatex.fmt
> warning: kpathsea: configuration file texmf.cnf not found in these directories

Will this be fixed on conda?

**Comment by philipcardiff** [comment]
@yichao-cai I just installed texlive and panda using conda and received the same error.

**Comment by jjaraalm** [comment]
Same issues. This seems unusable?

**Comment by flxai** [comment]
I can confirm this bug. Can one of the contributors reproduce this? @xhochy @ocefpaf @jayfurmanek 
Thanks for your time

**Comment by ocefpaf** [comment]
Folks, this package is unmaintained and we recommend tectonic or miktex instead, both available on conda-forge. I'm locking this issue but if anyone wants to pick this package up  and fix it, feel free to contact me or open an issue saying so.
