### ISSUE TITLE
PowerPC packages?

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/texlive-core-feedstock#29]
Hello!

I was wondering if there are any plans to build this package for `ppc64le`. AFAIK, this is the only dependency that is preventing `doxygen` from being built for that architecture.

Thanks!

**Comment by jayfurmanek** [comment]
I've been looking at this recently for ppc64le as well. I've tried, but this recipe seems to have mostly rotted out and likely doesn't build anywhere anymore. TexLive is quite complex and it doesn't help that they often change somethings around upstream.

There is a project called tinytex that might help inform and fix this package. If you are up for helping out, let me know.

**Comment by jaimergp** [comment]
I see. I have taken a look at `tinytex` and looks promising! I will keep an eye on this and might be able to help in the future.

Thank you!

**Comment by jayfurmanek** [comment]
@jaimergp packages are available for ppc64le. We can probably close this issue.

**Comment by jaimergp** [comment]
Oh, that's awesome! Thanks for the heads up!
