### ISSUE TITLE
Bump to Tex Live 2019

### ISSUE THREAD

**Issue by mjsteinbaugh** [conda-forge/texlive-core-feedstock#32]
I'm up for helping update this recipe to [Tex Live 2019](https://www.tug.org/texlive/), but I just wanted to double check that it wouldn't break existing dependencies on conda.

**Comment by jakirkham** [comment]
Help on this would be welcome. 🙂

**Comment by mjsteinbaugh** [comment]
OK cool @jakirkham I'll work on that when I have some free time.

**Comment by jakirkham** [comment]
Also thanks for working on this Michael.

**Comment by rluria14** [comment]
@mjsteinbaugh @jakirkham any updates on the 2019 version?

**Comment by jakirkham** [comment]
Not from me

**Comment by ngam** [comment]
we have the 2021 version now, so closing this.
