### ISSUE TITLE
Can't locate mktexlsr.pl in @INC

### ISSUE THREAD

**Issue by shiyi-pan** [conda-forge/texlive-core-feedstock#42]
Hi，when i used latex, i met the following error:

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=latex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt latex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: /gss1/home/hjb20181119/panyongpeng/ruanjian/texlive/tlpkg /gss1/home/hjb20181119/panyongpeng/ruanjian/texlive/texmf-dist/scripts/texlive /gss1/home/hjb20181119/panyongpeng/ruanjian/perl532/lib/site_perl/5.32.0/x86_64-linux-thread-multi /gss1/home/hjb20181119/panyongpeng/ruanjian/perl532/lib/site_perl/5.32.0 /gss1/home/hjb20181119/panyongpeng/ruanjian/perl532/lib/5.32.0/x86_64-linux-thread-multi /gss1/home/hjb20181119/panyongpeng/ruanjian/perl532/lib/5.32.0) at /gss1/home/hjb20181119/panyongpeng/ruanjian/texlive/bin/x86_64-pc-linux-gnu//mktexfmt line 23.
BEGIN failed--compilation aborted at /gss1/home/hjb20181119/panyongpeng/ruanjian/texlive/bin/x86_64-pc-linux-gnu//mktexfmt line 25.
I can't find the format file `latex.fmt'!

and I found the minimal-example tests for pdflatex and latex here https://github.com/conda-forge/texlive-core-feedstock/pull/20 and and when i test the latex like that :

printf '\\documentclass{article}\n\\begin{document}\n\\end{document}\n' | latex

I got the same error ,

This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=latex)
 restricted \write18 enabled.
**
kpathsea: Running mktexfmt latex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: /gss1/home/hjb20181119/panyongpeng/ruanjian/texlive/tlpkg /gss1/home/hjb20181119/panyongpeng/ruanjian/texlive/texmf-dist/scripts/texlive /gss1/home/hjb20181119/panyongpeng/ruanjian/perl532/lib/site_perl/5.32.0/x86_64-linux-thread-multi /gss1/home/hjb20181119/panyongpeng/ruanjian/perl532/lib/site_perl/5.32.0 /gss1/home/hjb20181119/panyongpeng/ruanjian/perl532/lib/5.32.0/x86_64-linux-thread-multi /gss1/home/hjb20181119/panyongpeng/ruanjian/perl532/lib/5.32.0) at /gss1/home/hjb20181119/panyongpeng/ruanjian/texlive/bin/x86_64-pc-linux-gnu//mktexfmt line 23.
BEGIN failed--compilation aborted at /gss1/home/hjb20181119/panyongpeng/ruanjian/texlive/bin/x86_64-pc-linux-gnu//mktexfmt line 25.
I can't find the format file `latex.fmt'!

could you help me fix the problem ? Thank you very much !

**Comment by shiyi-pan** [comment]
I'm sorry that i can't deal with it now.

**Comment by eschen42** [comment]
> 
> 
> I met same issue. have you ever solved the problem?
> 
> Here is my situation:
> 
> ```
> label: unnamed-chunk-12 (with options)
> List of 3
>  $ echo   : logi FALSE
>  $ message: logi FALSE
>  $ warning: logi FALSE
> 
>   |......................................................................| 100%
>    inline R code fragments
> 
> 
> output file: bookdown.knit.md
> 
> /home/sguo2/miniconda3/bin/pandoc +RTS -K512m -RTS bookdown.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output bookdown.tex --lua-filter /home/sguo2/miniconda3/lib/R/library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /home/sguo2/miniconda3/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/sguo2/miniconda3/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /tmp/Rtmpyt4zgc/file67803a604d0b --self-contained --table-of-contents --toc-depth 2 --number-sections --highlight-style tango --pdf-engine pdflatex --variable graphics --wrap preserve --variable tables=yes --standalone -Mhas-frontmatter=false
> ! kpathsea: Running mktexfmt pdflatex.fmt
> 
> ! Can't locate mktexlsr.pl in @INC (@INC contains: /home/sguo2/miniconda3/share/tlpkg /home/sguo2/miniconda3/share/texmf-dist/scripts/texlive /home/sguo2/perl5/lib/perl5/x86_64-linux-thread-multi /home/sguo2/perl5/lib/perl5 /home/sguo2/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/sguo2/miniconda3/lib/site_perl/5.26.2 /home/sguo2/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /home/sguo2/miniconda3/lib/5.26.2 .) at /home/sguo2/miniconda3/bin/mktexfmt line 23.
> 
> ! BEGIN failed--compilation aborted at /home/sguo2/miniconda3/bin/mktexfmt line 25.
> 
> Error: LaTeX failed to compile bookdown.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See bookdown.log for more info.
> ```

@Shicheng-Guo Yes, I got essentially the same thing when trying to run in my conda environment.

```
List of 1
 $ echo: logi FALSE


output file: QuantDataProcessingScript.knit.md

/home/art/miniforge3/envs/ppe6/bin/pandoc +RTS -K512m -RTS QuantDataProcessingScript.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output QuantDataProcessingScript.tex --lua-filter /home/art/miniforge3/envs/ppe6/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/art/miniforge3/envs/ppe6/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in'
! kpathsea: Running mktexfmt pdflatex.fmt

! Can't locate mktexlsr.pl in @INC (@INC contains: /home/art/miniforge3/envs/ppe6/share/tlpkg /home/art/miniforge3/envs/ppe6/share/texmf-dist/scripts/texlive /home/art/miniforge3/envs/ppe6/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/art/miniforge3/envs/ppe6/lib/site_perl/5.26.2 /home/art/miniforge3/envs/ppe6/lib/5.26.2/x86_64-linux-thread-multi /home/art/miniforge3/envs/ppe6/lib/5.26.2 .) at /home/art/miniforge3/envs/ppe6/bin/mktexfmt line 23.

! BEGIN failed--compilation aborted at /home/art/miniforge3/envs/ppe6/bin/mktexfmt line 25.

Error: LaTeX failed to compile QuantDataProcessingScript.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See QuantDataProcessingScript.log for more info.
```

```
 conda list | grep tinytex
r-tinytex                 0.34              r40hc72bb7e_0    conda-forge
```

**Comment by eschen42** [comment]
@Shicheng-Guo well, this worked for me; presumably the conda package for r-tinytex doesn't run the tinytex_install command, and perhaps it should.

```
Rscript -e 'tinytex::install_tinytex();rmarkdown::render("QuantDataProcessingScript.Rmd")'
```

**Comment by eschen42** [comment]
@Shicheng-Guo Here's what finally worked for me, after activating my environment (in which there already exists the `$CONDA_PREFIX/etc/conda/activate.d` directory):
```bash
echo 'bash -c "cd $CONDA_PREFIX/bin;ln -f -s x86_64-linux/pdflatex pdflatex"' > $CONDA_PREFIX/etc/conda/activate.d/tinytex_activate.sh
```
whereupon a symbolic link to pdflatex is on the PATH and
```
Rscript -e 'rmarkdown::render("QuantDataProcessingScript.Rmd")'
```
worked as expected.

**Comment by ngam** [comment]
this seems to be an unrelated issue? Closing for now.

@eschen42 reopen if you disagree
