### ISSUE TITLE
Is this library still supported?

### ISSUE THREAD

**Issue by tgmueller** [conda-forge/texlive-core-feedstock#79]
### Comment:

I"m getting fails with 

PS C:\Users\tgmue\Documents\texlive-core-feedstock> conda install texlive-core
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - texlive-core

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by jakirkham** [comment]
There are no Windows packages. Please see issue ( https://github.com/conda-forge/texlive-core-feedstock/issues/1 )

**Comment by jakirkham** [comment]
Duplicate of https://github.com/conda-forge/texlive-core-feedstock/issues/1
